import { Biodata } from '../types';

export const SAMPLE_DATA: Biodata = {
  fullName: 'Abdullah Ibn Al-Khattab',
  gender: 'Male',
  dob: '1995-05-15',
  age: '29',
  height: "5'10\"",
  weight: '75 kg',
  bloodGroup: 'O+',
  maritalStatus: 'Unmarried',
  nationality: 'Bangladeshi',
  presentAddress: 'Dhanmondi, Dhaka\nHouse #12, Road #4\nNear Lake Side',
  permanentAddress: 'Village: Alarpur, PO: Sadar\nDist: Chittagong\nPost Code: 4000',
  contactNumber: '01712-345678',
  email: 'abdullah.sample@example.com',
  religion: 'Islam',
  orientation: 'Sunni',
  madhhab: 'Hanafi',
  salahStatus: '5 times regularly since childhood.\nAlways try to perform in Jama\'ah (Mosque).',
  fastingStatus: 'Regularly observe',
  quranAbility: 'Can read fluently with proper Tajweed.\nAlso understands basic meanings of common Surahs.',
  religiousBackground: 'Completed basic Madrasa education (Qawmi) alongside SSC/HSC.',
  lifestyleSummary: 'Practicing Muslim. Follows the Sunnah in daily life. Avoids haram activities and maintains a modest lifestyle.',
  highestQualification: "Bachelor's of Science (BSc)\nFrom a reputed University\nMajor in Computer Science",
  institution: 'University of Dhaka',
  subject: 'Computer Science & Engineering',
  passingYear: '2018',
  additionalEducation: 'IELTS Band 7.5, Various professional certifications in Software Engineering.',
  occupation: 'Senior Software Engineer\nat a Global Tech Firm\nLead Mobile Developer',
  jobTitle: 'Senior Software Engineer',
  workplace: 'Tech Solutions Limited',
  income: '৳ 80,000+',
  workLocation: 'Gulshan, Dhaka',
  careerSummary: 'Working in the software industry for over 5 years. Passionate about building impactful products.',
  fatherName: 'Ibrahim Al-Khattab',
  fatherOccupation: 'Retired Government Official',
  motherName: 'Maryam Begum',
  motherOccupation: 'Homemaker',
  brothersCount: '1',
  sistersCount: '2',
  familyType: 'Nuclear',
  familyEnvironment: 'Practicing and Moderate',
  familyBackground: 'Our family values religious principles and education. We originate from Chittagong and have a respected lineage.',
  complexion: 'Fair',
  healthCondition: 'Excellent (No known chronic issues)',
  languages: ['Bangla', 'English', 'Arabic'],
  hobbies: 'Reading Islamic History, Playing Badminton, Coding',
  personality: 'Calm, patient, and family-oriented. Believes in mutual respect and Islamic values in a relationship.',
  lifestyle: 'Simple and organized. Enjoys spending time with family and attending religious circles.',
  futureGoals: 'To build a righteous family and contribute positively to the Ummah through my profession.',
  prefAgeRange: { min: '22', max: '26' },
  prefHeightRange: { min: "5'0\"", max: "5'6\"" },
  prefEducation: "Bachelor's",
  prefOccupation: 'Any respectful profession / Teacher preferred',
  prefLocation: 'Dhaka or Chittagong',
  prefReligiousQualities: 'Must be regular in Salah, observes proper Hijab, and has a willingness to grow in Deen.',
  prefFamilyExpectations: 'Respectful and understanding family with sound religious background.',
  prefOther: 'Preference for someone who values both worldly education and religious knowledge.\nShould be family-oriented and patient.',
  selfDescription: 'I am a humble servant of Allah trying my best to balance professional excellence and religious commitment.\nValues honest and clear communication.',
  marriageReason: 'To complete half of my Deen and build a family based on the Quran and Sunnah.',
  specialNotes: 'Interested in moving abroad for higher studies or career opportunities if required.',
  guardianContact: 'Please contact my father at 018xxxx-xxxxx for further inquiries.',
  customFields: [
    { id: '1', label: 'Favorite Islamic Books', value: '1. Ar-Raheeq Al-Makhtum\n2. Riyadh as-Salihin\n3. Don\'t Be Sad (La Tahzan)' }
  ],
};
